"""
Day 03 练习脚本 — 文件操作与异常处理
面向 C++ 开发者的 Python 学习

运行方式: python day03_basics.py
"""

import sys
import io
import os
import tempfile
import shutil

# 修复 Windows 终端 Unicode 输出问题
if sys.platform == "win32":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")


# ============================================================
# 准备：创建临时测试文件
# ============================================================
tmp_dir = tempfile.mkdtemp(prefix="pyday03_")
test_file = os.path.join(tmp_dir, "hello.txt")
with open(test_file, "w", encoding="utf-8") as f:
    f.write("Hello from Python!\n")
    f.write("Line 2: 中文测试\n")
    f.write("Line 3: end\n")

json_file = os.path.join(tmp_dir, "config.json")
csv_file = os.path.join(tmp_dir, "targets.csv")


# ============================================================
# 1. 文件操作基础
# ============================================================
# C++: std::ifstream file("hello.txt");
#       std::string line;
#       while (std::getline(file, line)) { ... }
#       file.close();
#
# Python: with open("hello.txt") as f:
#             for line in f: ...

print("=== 1. 文件操作基础 ===")

# --- 读取整个文件 ---
# C++: std::ostringstream buf; buf << file.rdbuf();
#      std::string content = buf.str();
with open(test_file, encoding="utf-8") as f:
    content = f.read()        # 读成一个大字符串
print(f"read(): {repr(content)}")


# --- 逐行读取 ---
# C++: while (std::getline(file, line)) { ... }
with open(test_file, encoding="utf-8") as f:
    lines = f.readlines()     # 读成 list[str]
print(f"readlines(): {lines}")

# --- 文件对象是迭代器 ---
# C++: 没有原生支持，需要手写循环
with open(test_file, encoding="utf-8") as f:
    for i, line in enumerate(f, 1):
        print(f"  Line {i}: {line.rstrip()}")

# --- 写入文件（"w" 覆盖模式）---
# C++: std::ofstream out("output.txt");
#      out << "data" << std::endl;
output_path = os.path.join(tmp_dir, "output.txt")
with open(output_path, "w", encoding="utf-8") as f:
    f.write("Generated by Python\n")
    f.writelines(["item1\n", "item2\n", "item3\n"])
print(f"\n写入文件: {output_path}")

# --- 追加模式 ---
# C++: std::ofstream out("log.txt", std::ios::app);
with open(output_path, "a", encoding="utf-8") as f:
    f.write("Appended line\n")

# --- 文件模式速查 ---
# "r": 只读（默认）
# "w": 写入（覆盖）
# "a": 追加
# "x": 排他创建（文件存在则报错）
# "r+": 读写
# "b": 二进制模式

print(f"\n文件模式测试——")
# "x" 模式：排他创建
new_file = os.path.join(tmp_dir, "exclusive.txt")
try:
    with open(new_file, "x") as f:  # 只有不存在时才创建
        f.write("only created once")
    print(f"  'x' 模式创建成功: {new_file}")
except FileExistsError:
    print(f"  'x' 模式: 文件已存在，创建失败（符合预期）")


# ============================================================
# 2. 路径处理 — pathlib
# ============================================================
# C++: namespace fs = std::filesystem;
#      fs::path p = fs::current_path() / "src" / "main.cpp";
#      p.filename();   // main.cpp
#      p.extension();  // .cpp
#
# Python: from pathlib import Path
#         p = Path.cwd() / "src" / "main.cpp"
#         p.name     # main.cpp
#         p.suffix   # .cpp

print("\n=== 2. 路径处理 — pathlib ===")

from pathlib import Path

# --- 路径对象创建 ---
current = Path.cwd()
print(f"当前目录: {current}")

# 拼接路径（/ 运算符重载，这是 Python 独有的）
src = current / "src" / "main.cpp"
print(f"拼接路径: {src}")

# --- Path 属性 ---
# C++: p.filename() / p.parent_path() / p.extension() / p.stem()
p = Path("D:/Projects/MyApp/src/core/renderer.cpp")
print(f"\n路径解析:")
print(f"  全路径:   {p}")
print(f"  文件名:   {p.name}")        # renderer.cpp
print(f"  后缀:     {p.suffix}")      # .cpp
print(f"  无后缀名: {p.stem}")        # renderer
print(f"  父目录:   {p.parent}")      # D:\Projects\MyApp\src\core

# --- 常用方法 ---
# 检查文件类型
print(f"\n文件和目录判断:")
print(f"  exists:      {Path(tmp_dir).exists()}")       # True
print(f"  is_dir:      {Path(tmp_dir).is_dir()}")       # True
print(f"  is_file:     {Path(test_file).is_file()}")    # True

# 快捷读写（不用 open！）
# C++: 没有这样的便利函数
Path(output_path).write_text("Quick write via Path!", encoding="utf-8")
content2 = Path(output_path).read_text(encoding="utf-8")
print(f"  read_text:   {content2}")

# 创建目录（mkdir -p）
# C++: fs::create_directories(path);
new_dir = Path(tmp_dir) / "build" / "obj" / "x64"
new_dir.mkdir(parents=True, exist_ok=True)
print(f"  创建目录:    {new_dir}")


# ============================================================
# 3. 数据序列化 — json / csv / struct
# ============================================================
# C++: 需要引入 nlohmann/json 等第三方库
# Python: 标准库内置 json, csv, struct

print("\n=== 3. 数据序列化 ===")

# --- JSON 序列化 ---
import json

config = {
    "name": "MyApp",
    "version": "1.0.0",
    "cxx_standard": 17,
    "targets": ["core", "renderer", "network"],
    "dependencies": {
        "core": ["renderer"],
        "renderer": [],
        "network": ["core"]
    }
}

# 写入 JSON — dump vs dumps
# C++: std::ofstream o("config.json"); o << config.dump(2);
with open(json_file, "w", encoding="utf-8") as f:
    json.dump(config, f, indent=2, ensure_ascii=False)
print(f"JSON 写入: {json_file}")

# 读取 JSON — load vs loads
with open(json_file, encoding="utf-8") as f:
    loaded = json.load(f)
print(f"JSON 读取: {loaded['name']} v{loaded['version']}")
print(f"  依赖数: {len(loaded['dependencies'])}")

# JSON 序列化字符串（不写文件）
json_str = json.dumps(config, indent=2)
print(f"  JSON 字符串长度: {len(json_str)} bytes")

# --- CSV 操作 ---
import csv

# 写入 CSV
# C++: 没有标准 CSV 库
with open(csv_file, "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerow(["Target", "Type", "Sources", "Size_KB"])
    writer.writerows([
        ["MyApp", "EXECUTABLE", 15, 248],
        ["Utils", "STATIC_LIB", 8, 96],
        ["Engine", "DYNAMIC_LIB", 32, 512],
    ])
print(f"\nCSV 写入: {csv_file}")

# 读取 CSV（DictReader — 最舒服的方式！）
# C++: 没有如此便利的抽象
with open(csv_file, encoding="utf-8") as f:
    reader = csv.DictReader(f)
    print("CSV 内容:")
    for row in reader:
        print(f"  {row['Target']}: {row['Type']}, {row['Sources']} sources")

# --- struct 二进制打包 ---
# C++: struct Header { uint32_t magic; uint16_t version; float scale; };
#      fwrite(&header, sizeof(Header), 1, file);
# Python: struct.pack("IHf", magic, version, scale)
import struct

# 格式符：I=uint32, H=uint16, f=float32
header_data = struct.pack("IHf", 0xDEADBEEF, 1, 1.5)
print(f"\nstruct 打包: {header_data.hex()} (length={len(header_data)})")

# 解包
magic, ver, scale = struct.unpack("IHf", header_data)
print(f"struct 解包: magic=0x{magic:08X}, version={ver}, scale={scale}")


# ============================================================
# 4. 异常处理
# ============================================================
# C++: try { ... } catch (const SomeException& e) { ... }
# Python: try/except/else/finally，四个子句！

print("\n=== 4. 异常处理 ===")

# --- 四个子句 ---
# else: 只有 try 成功时执行
# finally: 无论如何都执行（类似 C++ 的析构函数行为）
print("try/except/else/finally 演示:")

def risky_operation(filename, should_fail=False):
    """演示完整的异常处理"""
    result = None
    try:
        with open(filename, encoding="utf-8") as f:
            result = f.read()
        if should_fail:
            raise RuntimeError("模拟操作失败")
    except FileNotFoundError:
        print("  [except] 文件不存在")
    except PermissionError:
        print("  [except] 没有权限")
    except RuntimeError as e:
        print(f"  [except] 运行时错误: {e}")
    else:
        # C++ 没有 else！这里只有在 try 成功时才运行
        print(f"  [else] 读取成功: {len(result)} 字符")
    finally:
        # 类似 C++ 析构函数，无论如何都执行
        print(f"  [finally] 清理资源")

    return result

risky_operation(test_file)                # 成功
print()
risky_operation("nonexistent_file.txt")   # 文件不存在
print()
risky_operation(test_file, should_fail=True)  # 运行时错误

# --- EAFP vs LBYL ---
# LBYL (C++ 风格): 先检查
# EAFP (Python 风格): 先尝试，捕获异常
print("\nEAFP vs LBYL:")
d = {"name": "test", "version": 1}

# LBYL — C++ 风格
if "unknown_key" in d:
    print("  LBYL: found key")
else:
    print("  LBYL: key not found")

# EAFP — Python 风格（更推荐！）
try:
    val = d["unknown_key"]
    print(f"  EAFP: found value {val}")
except KeyError:
    print("  EAFP: key not found")


# ============================================================
# 5. 自定义异常
# ============================================================
# C++: class MyError : public std::exception { ... };
#       throw MyError("msg");
# Python: class MyError(Exception): pass
#         raise MyError("msg")

print("\n=== 5. 自定义异常 ===")

# 一行定义异常类！
# C++ 需要写完整的类定义 + what() 方法
class BuildError(Exception):
    """所有构建相关异常的基类"""
    pass

class CompileError(BuildError):
    """编译阶段错误"""
    pass

class LinkError(BuildError):
    """链接阶段错误"""
    pass

# 异常层次的使用
def build_project(target: str, fail_at: str = "") -> str:
    """模拟构建过程"""
    if fail_at == "compile":
        raise CompileError(f"编译失败: {target}/main.cpp:42: error: undefined reference")
    if fail_at == "link":
        raise LinkError(f"链接失败: undefined symbol in {target}")
    return f"{target} 构建成功"

# 测试正常构建
print(f"正常构建: {build_project('MyApp')}")

# 捕获子类异常
for fail_type in ["compile", "link"]:
    try:
        build_project("MyApp", fail_at=fail_type)
    except CompileError as e:
        print(f"编译错误: {e}")
    except LinkError as e:
        print(f"链接错误: {e}")
    except BuildError as e:
        print(f"构建错误: {e}")  # 捕获所有构建错误

# --- raise from — 异常链 ---
# C++: std::throw_with_nested 概念类似但使用繁琐
print("\n异常链 (raise from):")
try:
    with open("nonexistent.json") as f:
        json.load(f)
except FileNotFoundError as e:
    # 包装成更语义化的错误
    try:
        raise RuntimeError("配置文件加载失败") from e
    except RuntimeError as wrapped:
        print(f"  原始错误: {wrapped.__cause__}")
        print(f"  包装错误: {wrapped}")
        # __cause__ 属性保存了原始异常


# ============================================================
# 6. 上下文管理器
# ============================================================
# C++: RAII (构造函数获取资源，析构函数释放)
# Python: with 语句 + __enter__ / __exit__
#        或者 @contextmanager 装饰器

print("\n=== 6. 上下文管理器 ===")

from contextlib import contextmanager

# --- 方式1：基于类 ---
class Timer:
    """计时器上下文管理器"""
    def __enter__(self):
        import time
        self.start = time.perf_counter()
        return self  # 返回给 as 后面的变量

    def __exit__(self, exc_type, exc_val, exc_tb):
        import time
        elapsed = time.perf_counter() - self.start
        print(f"  类方式耗时: {elapsed:.6f}s")
        # 返回 False 表示不抑制异常

with Timer():
    total = sum(range(1000000))

# --- 方式2：基于生成器（更简洁！）---
@contextmanager
def timed_block(name: str = ""):
    """计时上下文管理器 — 基于装饰器"""
    import time
    label = f" [{name}]" if name else ""
    start = time.perf_counter()
    try:
        yield  # 这是 with 块的执行点
    finally:
        elapsed = time.perf_counter() - start
        print(f"  装饰器方式{label}耗时: {elapsed:.6f}s")

with timed_block("计算斐波那契"):
    a, b = 0, 1
    for _ in range(100000):
        a, b = b, a + b

# --- 实用上下文管理器：临时目录 ---
@contextmanager
def temp_working_dir(path: str):
    """临时切换工作目录，自动恢复（类似 pushd/popd）"""
    old = os.getcwd()
    os.chdir(path)
    try:
        yield
    finally:
        os.chdir(old)  # 无论如何都恢复

with temp_working_dir(tmp_dir):
    print(f"  切换到临时目录: {os.getcwd()}")
    # 在这里做事情...
print(f"  已恢复目录: {os.getcwd()}")

# --- suppress：优雅地忽略特定异常 ---
from contextlib import suppress

# C++: try { deleteFile(); } catch (...) { /* ignore */ }
# 但这样会吞掉所有错误！
# Python: with suppress(FileNotFoundError):
#             os.remove("may_not_exist.txt")
with suppress(FileNotFoundError):
    os.remove("definitely_not_exist.txt")
    print("  不会执行到这里")


# ============================================================
# 7. 实战综合：项目文件统计器
# ============================================================
print("\n=== 7. 实战综合：项目文件统计器 ===")

from dataclasses import dataclass

@dataclass
class FileStats:
    """文件统计信息"""
    path: str
    total_lines: int
    code_lines: int
    blank_lines: int
    comment_lines: int

def analyze_cpp_file(filepath: Path) -> FileStats | None:
    """分析单个 C++ 文件的行数组成"""
    try:
        with open(filepath, encoding="utf-8", errors="replace") as f:
            lines = f.readlines()
    except (OSError, UnicodeDecodeError):
        return None

    code = blank = comment = 0
    for line in lines:
        stripped = line.strip()
        if not stripped:
            blank += 1
        elif stripped.startswith("//"):
            comment += 1
        elif stripped.startswith("/*"):
            comment += 1
        elif stripped.startswith("*"):
            comment += 1
        else:
            code += 1

    return FileStats(
        path=str(filepath),
        total_lines=len(lines),
        code_lines=code,
        blank_lines=blank,
        comment_lines=comment,
    )

# 模拟创建几个测试文件
test_files_dir = Path(tmp_dir) / "cpp_test"
test_files_dir.mkdir(exist_ok=True)

# 模拟 main.cpp
(test_files_dir / "main.cpp").write_text("""#include <iostream>

int main() {
    // 打印问候语
    std::cout << "Hello, World!" << std::endl;
    return 0;  // 成功返回
}
""", encoding="utf-8")

# 模拟 utils.h
(test_files_dir / "utils.h").write_text("""#pragma once

#include <string>
#include <vector>

// 工具函数声明
namespace utils {
    std::string trim(const std::string& s);
    std::vector<std::string> split(const std::string& s, char delim);
}
""", encoding="utf-8")

# 扫描并分析
print(f"扫描目录: {test_files_dir}")
cpp_files = list(test_files_dir.glob("*.cpp")) + list(test_files_dir.glob("*.h"))
total_code = 0
for fpath in cpp_files:
    stats = analyze_cpp_file(fpath)
    if stats:
        print(f"  {fpath.name}: {stats.total_lines} 行 "
              f"({stats.code_lines} code, {stats.blank_lines} blank, "
              f"{stats.comment_lines} comment)")
        total_code += stats.code_lines
print(f"  总计有效代码行: {total_code}")

# 生成 JSON 报告
report = {
    "project_root": str(test_files_dir),
    "total_files": len(cpp_files),
    "total_code_lines": total_code,
    "files": []
}
for fpath in cpp_files:
    stats = analyze_cpp_file(fpath)
    if stats:
        report["files"].append({
            "name": fpath.name,
            "lines": stats.total_lines,
            "code": stats.code_lines,
            "blank": stats.blank_lines,
            "comment": stats.comment_lines,
        })

report_file = Path(tmp_dir) / "scan_report.json"
with open(report_file, "w", encoding="utf-8") as f:
    json.dump(report, f, indent=2, ensure_ascii=False)
print(f"\n报告已生成: {report_file}")


# ============================================================
# 清理
# ============================================================
shutil.rmtree(tmp_dir, ignore_errors=True)

print("\n" + "=" * 50)
print("Day 03 练习脚本运行完毕！")
print("关键收获:")
print("  1. 用 with 语句打开文件，自动管理资源")
print("  2. pathlib 是处理路径的最佳选择（类比 std::filesystem）")
print("  3. json/csv 内置模块让序列化变得简单")
print("  4. try/except/else/finally 四件套比 C++ 更灵活")
print("  5. @contextmanager 让自定义上下文管理器变得超简单")
print("=" * 50)
