#!/usr/bin/env python3
"""
Day 10 综合实战：C++ 项目工具链
- C++ 开发者学 Python 的最终章，把前 9 天所有知识串起来
- 每个知识点带 C++ 对比注释
"""

import os
import sys
import json
import re
import shutil
import subprocess
import pathlib
import hashlib
import time
import tempfile
import argparse
import textwrap
from datetime import datetime
from string import Template
from collections import defaultdict, Counter
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Tuple
from contextlib import contextmanager

# ============================================================
# 1. 项目脚手架 —— Python 生成 C++ 项目结构
# ============================================================
# C++ 对比：C++ 项目需要手动创建目录、CMakeLists.txt、头文件等
# Python 可以一键生成标准项目骨架

def demo_project_scaffold():
    """演示：自动生成 C++ 项目骨架"""
    print("\n=== 1. 项目脚手架 ===")

    # C++ 方式（手动）：逐个 mkdir、touch、编写 CMakeLists.txt
    # Python 方式：用 pathlib + Template 一键生成

    project_name = "demo_cpp_project"
    project_dir = pathlib.Path(tempfile.mkdtemp()) / project_name

    # 定义项目模板
    cmake_template = Template(textwrap.dedent("""\
        cmake_minimum_required(VERSION 3.16)
        project($project_name VERSION $version LANGUAGES CXX)

        set(CMAKE_CXX_STANDARD $cxx_standard)
        set(CMAKE_CXX_STANDARD_REQUIRED ON)

        # Source files
        file(GLOB_RECURSE SOURCES "src/*.cpp")
        file(GLOB_RECURSE HEADERS "include/*.h")

        add_executable($project_name $${SOURCES} $${HEADERS})
        target_include_directories($project_name PRIVATE include)

        # Testing
        option(BUILD_TESTS "Build tests" ON)
        if(BUILD_TESTS)
            enable_testing()
            add_subdirectory(tests)
        endif()
    """))

    main_cpp_template = Template(textwrap.dedent("""\
        #include <iostream>
        #include "$header_name"

        int main() {
            std::cout << "$project_name v$version" << std::endl;
            auto result = $project_name::hello();
            std::cout << result << std::endl;
            return 0;
        }
    """))

    header_template = Template(textwrap.dedent("""\
        #pragma once
        #include <string>

        namespace $project_name {
            std::string hello();
        }
    """))

    source_template = Template(textwrap.dedent("""\
        #include "$header_name"

        namespace $project_name {
            std::string hello() {
                return "Hello from $project_name!";
            }
        }
    """))

    # 生成目录结构
    dirs = ["src", "include", "tests", "docs", "scripts"]
    for d in dirs:
        (project_dir / d).mkdir(parents=True, exist_ok=True)

    # 生成 CMakeLists.txt
    cmake_content = cmake_template.substitute(
        project_name=project_name,
        version="0.1.0",
        cxx_standard="17"
    )
    (project_dir / "CMakeLists.txt").write_text(cmake_content, encoding="utf-8")

    # 生成头文件
    header_name = f"{project_name}.h"
    header_content = header_template.substitute(
        project_name=project_name,
        header_name=header_name
    )
    (project_dir / "include" / header_name).write_text(header_content, encoding="utf-8")

    # 生成源文件
    source_content = source_template.substitute(
        project_name=project_name,
        header_name=header_name
    )
    (project_dir / "src" / f"{project_name}.cpp").write_text(source_content, encoding="utf-8")

    # 生成 main.cpp
    main_content = main_cpp_template.substitute(
        project_name=project_name,
        version="0.1.0",
        header_name=header_name
    )
    (project_dir / "src" / "main.cpp").write_text(main_content, encoding="utf-8")

    # 生成 README
    readme = f"# {project_name}\n\nVersion 0.1.0\n\nGenerated by Python toolchain.\n"
    (project_dir / "README.md").write_text(readme, encoding="utf-8")

    # 列出生成的文件
    print(f"项目骨架已生成：{project_dir}")
    for f in sorted(project_dir.rglob("*")):
        if f.is_file():
            rel = f.relative_to(project_dir)
            print(f"  {rel} ({f.stat().st_size} bytes)")

    # 清理临时目录
    shutil.rmtree(project_dir)
    print("(临时项目已清理)")


# ============================================================
# 2. 代码度量分析 —— 扫描 C++ 代码统计
# ============================================================
# C++ 对比：C++ 需要第三方工具（如 cppcheck、lint）或手动统计
# Python 用正则 + pathlib 轻量统计，灵活定制

def demo_code_metrics():
    """演示：C++ 代码度量分析"""
    print("\n=== 2. 代码度量分析 ===")

    # 生成示例 C++ 文件进行分析
    sample_cpp = textwrap.dedent("""\
        #include <iostream>
        #include <vector>
        #include <string>
        #include <algorithm>

        // Utility function
        inline int add(int a, int b) { return a + b; }

        class Processor {
        private:
            std::vector<int> data_;
            std::string name_;
            int count_ = 0;
        public:
            Processor(const std::string& name) : name_(name) {}

            void addData(int value) {
                data_.push_back(value);
                count_++;
            }

            int process() {
                // TODO: implement complex processing
                int sum = 0;
                for (int v : data_) {
                    sum += v;
                }
                return sum;
            }

            std::string getName() const { return name_; }

            ~Processor() = default;
        };

        int main() {
            Processor p("test");
            p.addData(1);
            p.addData(2);
            std::cout << p.process() << std::endl;
            return 0;
        }
    """)

    # 写入临时文件
    tmp_dir = pathlib.Path(tempfile.mkdtemp())
    cpp_file = tmp_dir / "sample.cpp"
    cpp_file.write_text(sample_cpp, encoding="utf-8")

    # 统计函数数量 —— C++ 方式：grep + wc；Python 方式：正则直接匹配
    func_pattern = re.compile(
        r'(?:inline\s+)?(?:static\s+)?(?:virtual\s+)?'
        r'(?:void|int|float|double|string|auto|bool|size_t)\s+'
        r'(\w+)\s*\([^)]*\)\s*(?:const)?\s*\{',
        re.MULTILINE
    )
    functions = func_pattern.findall(sample_cpp)
    print(f"函数数量：{len(functions)} → {functions}")

    # 统计类数量
    class_pattern = re.compile(r'class\s+(\w+)\s*(?:final)?\s*\{', re.MULTILINE)
    classes = class_pattern.findall(sample_cpp)
    print(f"类数量：{len(classes)} → {classes}")

    # 统计 TODO/FIXME
    todo_pattern = re.compile(r'(TODO|FIXME|HACK|BUG)\b', re.IGNORECASE)
    todos = todo_pattern.findall(sample_cpp)
    print(f"TODO/FIXME 数量：{len(todos)} → {todos}")

    # 统计 include 数量
    include_pattern = re.compile(r'#include\s+[<"](\w+)[>"]', re.MULTILINE)
    includes = include_pattern.findall(sample_cpp)
    print(f"#include 数量：{len(includes)} → {includes}")

    # 计算圈复杂度（简化版：统计 if/else/for/while/switch/case）
    branch_pattern = re.compile(r'\b(if|else|for|while|switch|case|catch|&&|\|\|)\b')
    branches = len(branch_pattern.findall(sample_cpp))
    print(f"简化圈复杂度（分支数）：{branches}")

    # 行数统计
    lines = sample_cpp.split('\n')
    total_lines = len(lines)
    code_lines = len([l for l in lines if l.strip() and not l.strip().startswith('//')])
    comment_lines = len([l for l in lines if l.strip().startswith('//')])
    blank_lines = total_lines - code_lines - comment_lines
    print(f"总行数：{total_lines} | 代码行：{code_lines} | 注释行：{comment_lines} | 空行：{blank_lines}")

    shutil.rmtree(tmp_dir)


# ============================================================
# 3. 构建日志解析 —— 正则提取编译错误
# ============================================================
# C++ 对比：手动翻日志找错误；Python 自动解析+分类+汇总

def demo_build_log_parser():
    """演示：解析 C++ 构建日志"""
    print("\n=== 3. 构建日志解析 ===")

    # 模拟 gcc/clang 编译日志
    sample_log = textwrap.dedent("""\
        /home/user/project/src/main.cpp:15:10: error: 'cout' was not declared in this scope
        /home/user/project/src/utils.cpp:42:5: warning: unused variable 'x' [-Wunused-variable]
        /home/user/project/src/parser.cpp:88:20: error: no matching function for call to 'parse'
        /home/user/project/src/main.cpp:22:1: error: expected ';' after expression
        /home/user/project/src/io.cpp:7:3: warning: comparison between signed and unsigned [-Wsign-compare]
        /home/user/project/src/main.cpp:15:10: note: suggested alternative: 'std::cout'
        /home/user/project/include/types.h:5:2: error: 'string' does not name a type
        /home/user/project/src/utils.cpp:42:5: note: remove 'x' if unused
        /home/user/project/src/algo.cpp:100:8: warning: implicit conversion from 'float' to 'int' [-Wconversion]
        BUILD FAILED: 4 errors, 3 warnings
    """)

    # 正则提取 error/warning/note
    # C++ 方式：写复杂脚本或用 shell 管道 grep；Python 方式：正则一步到位
    error_re = re.compile(r'^(.+?):(\d+):(\d+): (error|warning|note): (.+)$', re.MULTILINE)

    errors = []
    warnings = []
    notes = []

    for m in error_re.finditer(sample_log):
        file_path, line, col, level, message = m.groups()
        entry = {"file": file_path, "line": int(line), "col": int(col), "message": message}
        if level == "error":
            errors.append(entry)
        elif level == "warning":
            warnings.append(entry)
        else:
            notes.append(entry)

    print(f"错误：{len(errors)} 个")
    for e in errors:
        print(f"  {e['file']}:{e['line']} → {e['message']}")

    print(f"警告：{len(warnings)} 个")
    for w in warnings:
        print(f"  {w['file']}:{w['line']} → {w['message']}")

    # 按文件分组统计 —— defaultdict 比 C++ unordered_map 更方便
    by_file = defaultdict(lambda: {"errors": 0, "warnings": 0})
    for e in errors:
        by_file[e["file"]]["errors"] += 1
    for w in warnings:
        by_file[w["file"]]["warnings"] += 1

    print("\n按文件统计：")
    for f, counts in sorted(by_file.items()):
        print(f"  {f}: {counts['errors']} errors, {counts['warnings']} warnings")


# ============================================================
# 4. 代码生成器 —— 从 JSON 规范生成 C++ 类
# ============================================================
# C++ 对比：手写每个类、构造函数、getter/setter
# Python 从数据模型自动生成，节省大量重复劳动

def demo_code_generator():
    """演示：从 JSON 规范生成 C++ 类"""
    print("\n=== 4. 代码生成器 ===")

    # JSON 规范定义数据模型
    spec = {
        "namespace": "app",
        "classes": [
            {
                "name": "User",
                "fields": [
                    {"name": "id", "type": "int", "default": "0"},
                    {"name": "name", "type": "std::string", "default": "\"\""},
                    {"name": "email", "type": "std::string", "default": "\"\""},
                    {"name": "active", "type": "bool", "default": "true"}
                ],
                "methods": ["toString"]
            },
            {
                "name": "Config",
                "fields": [
                    {"name": "port", "type": "int", "default": "8080"},
                    {"name": "host", "type": "std::string", "default": "\"localhost\""},
                    {"name": "verbose", "type": "bool", "default": "false"}
                ],
                "methods": ["toString", "validate"]
            }
        ]
    }

    for cls in spec["classes"]:
        print(f"\n--- 生成 {cls['name']} 类 ---")

        # 生成头文件
        header_lines = [
            f"#pragma once",
            f"#include <string>",
            f"#include <sstream>",
            f"",
            f"namespace {spec['namespace']} {{",
            f"",
            f"class {cls['name']} {{",
            f"private:",
        ]
        for f in cls["fields"]:
            header_lines.append(f"    {f['type']} {f['name']}_ = {f['default']};")

        header_lines.extend([
            f"public:",
            f"    // Constructors",
            f"    {cls['name']}() = default;",
        ])

        # 生成带参数的构造函数
        params = ", ".join(f"{f['type']} {f['name']}" for f in cls["fields"])
        init_list = ", ".join(f"{f['name']}_({f['name']})" for f in cls["fields"])
        header_lines.append(f"    {cls['name']}({params}) : {init_list} {{}}")

        # 生成 getter/setter
        for f in cls["fields"]:
            header_lines.append(f"")
            # getter —— C++ const 引用返回 vs Python @property
            if f["type"] == "std::string":
                header_lines.append(f"    const {f['type']}& {f['name']}() const {{ return {f['name']}_; }}")
            else:
                header_lines.append(f"    {f['type']} {f['name']}() const {{ return {f['name']}_; }}")
            # setter
            if f["type"] == "std::string":
                header_lines.append(f"    void set_{f['name']}(const {f['type']}& val) {{ {f['name']}_ = val; }}")
            else:
                header_lines.append(f"    void set_{f['name']}({f['type']} val) {{ {f['name']}_ = val; }}")

        # 生成指定方法
        if "toString" in cls["methods"]:
            header_lines.extend([
                f"",
                f"    std::string toString() const {{",
                f"        std::ostringstream oss;",
            ])
            for f in cls["fields"]:
                header_lines.append(f"        oss << \"{f['name']}=\" << {f['name']}_ << \";\";")
            header_lines.extend([
                f"        return oss.str();",
                f"    }}",
            ])

        if "validate" in cls["methods"]:
            header_lines.extend([
                f"",
                f"    bool validate() const {{",
                f"        return port_ > 0 && port_ < 65536 && !host_.empty();",
                f"    }}",
            ])

        header_lines.extend([
            f"}};",
            f"",
            f"}} // namespace {spec['namespace']}",
        ])

        header_content = "\n".join(header_lines)
        print(header_content)


# ============================================================
# 5. 配置驱动构建 —— JSON 配置 + subprocess
# ============================================================
# C++ 对比：CMake + 手写脚本；Python 用 JSON 配置+subprocess 统一管理

def demo_config_driven_build():
    """演示：配置驱动的批量构建"""
    print("\n=== 5. 配置驱动构建 ===")

    # 模拟构建配置
    build_config = {
        "project_root": "/tmp/cpp_project",
        "targets": [
            {"name": "core", "sources": ["core.cpp", "utils.cpp"], "type": "library"},
            {"name": "app", "sources": ["main.cpp"], "type": "executable", "depends": ["core"]},
            {"name": "test_app", "sources": ["test_main.cpp"], "type": "executable", "depends": ["core"]}
        ],
        "compiler": "g++",
        "flags": ["-std=c++17", "-Wall", "-O2"],
        "output_dir": "build"
    }

    print("构建配置：")
    print(json.dumps(build_config, indent=2, ensure_ascii=False))

    # 模拟构建过程（subprocess 调用编译器）
    # C++ 方式：Makefile/CMake 一条条规则；Python 方式：读配置 → 动态构建命令
    print("\n模拟构建命令生成：")
    common_flags = " ".join(build_config["flags"])

    for target in build_config["targets"]:
        sources = " ".join(target["sources"])
        if target["type"] == "library":
            output = f"{target['name']}.a"
            cmd = f"{build_config['compiler']} {common_flags} -c {sources} -o {output}"
        else:
            output = target["name"]
            deps = " ".join(f"-l{d}" for d in target.get("depends", []))
            cmd = f"{build_config['compiler']} {common_flags} {sources} {deps} -o {output}"
        print(f"  [{target['name']}] {cmd}")


# ============================================================
# 6. 文件变更监控 —— 增量构建的基石
# ============================================================
# C++ 对比：CMake 用文件时间戳判断是否需要重新编译
# Python 用 hashlib 做内容哈希，更精确（不受 touch 影响）

def demo_file_change_tracking():
    """演示：文件内容哈希追踪变更"""
    print("\n=== 6. 文件变更监控 ===")

    # 生成临时测试文件
    tmp_dir = pathlib.Path(tempfile.mkdtemp())
    file1 = tmp_dir / "a.cpp"
    file2 = tmp_dir / "b.cpp"

    file1.write_text("int main() { return 0; }")
    file2.write_text("void foo() {}")

    # 计算内容哈希 —— C++ 方式：手动比较时间戳；Python：hashlib 内容哈希更可靠
    def file_hash(path):
        """计算文件 SHA256 哈希"""
        h = hashlib.sha256()
        h.update(path.read_bytes())
        return h.hexdigest()[:16]  # 取前16位足够判断变更

    # 第一次记录哈希
    hash_cache = {}
    for f in [file1, file2]:
        hash_cache[str(f)] = file_hash(f)
    print("初始哈希：")
    for p, h in hash_cache.items():
        print(f"  {pathlib.Path(p).name}: {h}")

    # 修改文件
    file1.write_text("int main() { return 42; }")  # 内容变了
    # file2 不变

    # 检测变更
    changed = []
    for f in [file1, file2]:
        current_hash = file_hash(f)
        old_hash = hash_cache[str(f)]
        if current_hash != old_hash:
            changed.append(f.name)
            print(f"  {f.name}: 变更检测！{old_hash} → {current_hash}")
        else:
            print(f"  {f.name}: 无变更（哈希一致）")

    print(f"\n需要重新编译的文件：{changed}")

    shutil.rmtree(tmp_dir)


# ============================================================
# 7. 性能计时器 —— Python vs C++ 基准对比
# ============================================================
# C++ 对比：<chrono> 高精度计时；Python time.perf_counter 更简洁

def demo_performance_timer():
    """演示：性能计时与基准测试"""
    print("\n=== 7. 性能计时器 ===")

    # C++ 方式：
    # auto start = std::chrono::high_resolution_clock::now();
    # ... code ...
    # auto end = std::chrono::high_resolution_clock::now();
    # auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count();

    # Python 方式：更简洁，用 contextmanager 封装
    @contextmanager
    def timer(name):
        start = time.perf_counter()
        yield
        elapsed = time.perf_counter() - start
        print(f"  [{name}] 耗时 {elapsed:.4f}s ({elapsed*1000:.2f}ms)")

    # 对比不同算法性能
    data = list(range(10000))

    with timer("列表求和 - sum()"):
        total = sum(data)

    with timer("列表求和 - 手动循环"):
        total2 = 0
        for x in data:
            total2 += x

    with timer("列表求和 - reduce"):
        from functools import reduce
        total3 = reduce(lambda a, b: a + b, data)

    assert total == total2 == total3, "结果不一致"
    print(f"  三种方式结果一致：{total}")


# ============================================================
# 8. 测试发现与运行 —— 自动化 C++ 单元测试
# ============================================================
# C++ 对比：CTest 需要手动注册；Python 自动发现 test_*.py

def demo_test_discovery():
    """演示：测试自动发现与运行"""
    print("\n=== 8. 测试发现与运行 ===")

    # 生成模拟测试文件
    tmp_dir = pathlib.Path(tempfile.mkdtemp())
    test_dir = tmp_dir / "tests"
    test_dir.mkdir()

    # 模拟几个 C++ 测试文件名
    test_files = [
        "test_user.cpp",
        "test_config.cpp",
        "test_parser.cpp",
        "test_utils.cpp",
    ]
    for tf in test_files:
        (test_dir / tf).write_text(f"// {tf} - test file\n", encoding="utf-8")

    # 自动发现测试 —— C++ 方式：在 CMakeLists.txt 手动 add_test
    # Python 方式：glob + 正则模式自动发现
    discovered = list(test_dir.glob("test_*.cpp"))
    print(f"自动发现 {len(discovered)} 个测试：")
    for t in sorted(discovered):
        print(f"  {t.name}")

    # 模拟运行测试并收集结果
    # dataclass 比 C++ struct 更方便（自动生成 __init__ 等）
    @dataclass
    class TestResult:
        name: str
        passed: bool
        duration_ms: float
        output: str = ""

    # 模拟测试结果
    results = [
        TestResult("test_user", True, 12.5),
        TestResult("test_config", True, 8.3),
        TestResult("test_parser", False, 45.2, "Assertion failed: parse(\"{bad}\") returned null"),
        TestResult("test_utils", True, 3.1),
    ]

    passed = sum(1 for r in results if r.passed)
    failed = len(results) - passed
    total_time = sum(r.duration_ms for r in results)

    print(f"\n测试汇总：{passed} passed, {failed} failed, 总耗时 {total_time:.1f}ms")
    for r in results:
        status = "✅ PASS" if r.passed else "❌ FAIL"
        print(f"  {status} {r.name} ({r.duration_ms:.1f}ms)")
        if not r.passed:
            print(f"       → {r.output}")

    # 生成 JUnit XML 格式 —— C++ 项目 CI/CD 常用
    xml_lines = ['<testsuite tests="4" failures="1" time="{:.1f}">'.format(total_time)]
    for r in results:
        xml_lines.append(f'  <testcase classname="{spec.get("namespace", "app")}" name="{r.name}" time="{r.duration_ms/1000:.3f}">')
        if not r.passed:
            xml_lines.append(f'    <failure message="{r.output}"/>')
        xml_lines.append(f'  </testcase>')
    xml_lines.append('</testsuite>')
    print("\nJUnit XML 格式（CI/CD 集成用）：")
    print("\n".join(xml_lines))

    shutil.rmtree(tmp_dir)


# ============================================================
# 9. 综合工具链 —— 把所有模块串起来
# ============================================================
# C++ 对比：Makefile/CMake 是独立体系，各工具碎片化
# Python：一个脚本统一管理，模块化+可扩展

def demo_full_toolchain():
    """演示：完整工具链集成"""
    print("\n=== 9. 综合工具链集成 ===")

    # 定义工具链命令 —— argparse 比 C++ 命令行解析更简洁
    print("工具链支持的操作：")
    operations = {
        "init":    "创建项目骨架（项目脚手架）",
        "build":   "配置驱动的增量构建",
        "test":    "自动发现并运行测试",
        "metrics": "代码度量分析",
        "log":     "构建日志解析",
        "gen":     "从 JSON 规范生成 C++ 类",
        "bench":   "性能基准测试",
    }
    for op, desc in operations.items():
        print(f"  {op:10s} → {desc}")

    # 模拟完整工作流
    print("\n模拟完整工作流：")

    workflow_steps = [
        ("1. init", "生成项目骨架 → src/, include/, tests/, CMakeLists.txt"),
        ("2. gen",  "从 JSON 规范 → User.h, Config.h（代码生成）"),
        ("3. build", "读取 build_config.json → g++ -std=c++17 ...（增量构建）"),
        ("4. test",  "glob test_*.cpp → 发现4个测试 → 运行+汇总+JUnit XML"),
        ("5. metrics","扫描 *.cpp → 5 functions, 1 class, 1 TODO（代码度量）"),
        ("6. log",   "解析编译日志 → 4 errors, 3 warnings（日志分析）"),
        ("7. bench", "perf_counter → sum/loop/reduce 对比（基准测试）"),
    ]

    for step, desc in workflow_steps:
        print(f"  {step:12s}: {desc}")

    print("\n💡 10天学习旅程到此完成！")
    print("   你已经掌握了用 Python 辅助 C++ 开发的核心技能：")
    print("   - Python 基础语法与 C++ 的对比理解")
    print("   - 文件操作、异常处理、正则表达式")
    print("   - subprocess 调用 C++ 程序")
    print("   - ctypes/pybind11 混合编程")
    print("   - CMake 辅助与批量编译")
    print("   - 综合工具链：项目脚手架 + 代码生成 + 构建自动化 + 测试 + 日志分析")
    print("   🎉 继续探索，Python 让 C++ 开发更高效！")


# ============================================================
# 主入口
# ============================================================

# 全局变量（供 demo_test_discovery 使用）
spec = {"namespace": "app"}

def main():
    parser = argparse.ArgumentParser(description="Day 10: 综合实战 —— C++ 项目工具链")
    parser.add_argument("--demo", choices=["all", "1", "2", "3", "4", "5", "6", "7", "8", "9"],
                        default="all", help="选择演示模块（1-9 或 all）")
    args = parser.parse_args()

    demos = {
        "1": demo_project_scaffold,
        "2": demo_code_metrics,
        "3": demo_build_log_parser,
        "4": demo_code_generator,
        "5": demo_config_driven_build,
        "6": demo_file_change_tracking,
        "7": demo_performance_timer,
        "8": demo_test_discovery,
        "9": demo_full_toolchain,
    }

    print("=" * 60)
    print("Day 10 综合实战：C++ 项目工具链")
    print("=" * 60)

    if args.demo == "all":
        for key in sorted(demos.keys()):
            demos[key]()
    else:
        demos[args.demo]()

    print("\n" + "=" * 60)
    print("完成！运行方式：")
    print("  python day10_basics.py          # 运行所有演示")
    print("  python day10_basics.py --demo 3 # 只运行构建日志解析")
    print("=" * 60)


if __name__ == "__main__":
    main()
